version: '3.8'

services:
  swindlr:
    build: 
      context: ./swindlr
      dockerfile: Dockerfile
    volumes: 
      - ./swindlr_testenv/swindlr_conf/config.yaml:/root/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      - nodeapp1
      - nodeapp2
      - nodeapp3
    command: ["./swindlr"]

  nodeapp1:
    build: 
      context: ./swindlr_testenv
      dockerfile: Dockerfile
    environment:
      - CONTAINER_ID=nodeapp1

  nodeapp2:
    build: 
      context: ./swindlr_testenv
      dockerfile: Dockerfile
    environment:
      - CONTAINER_ID=nodeapp2

  nodeapp3:
    build: 
      context: ./swindlr_testenv
      dockerfile: Dockerfile
    environment:
      - CONTAINER_ID=nodeapp3
