name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download dependencies
      run: go mod download
      working-directory: ./swindlr

    - name: Test
      run: go test -v ./...
      working-directory: ./swindlr

    - name: Build
      run: go build ./...
      working-directory: ./swindlr
