port: 8081
apiPort: 8082
backends:
  - http://nodeapp1:3000
  - http://nodeapp2:3000
  - http://nodeapp3:3000
use_ssl: true
ssl_cert_file: "/root/ssl/cert.pem"
ssl_key_file: "/root/ssl/key.pem" 
rate_limiting:
  rate: 10
  bucket_size: 5